"""Regenerate every table in the README from the code.

Run:  python scripts/generate_tables.py
Writes results/kv-analysis.md. No number in the README is typed by hand.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from attn.kv_memory import GPUS, MODELS, hypothetical_mha  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "results" / "kv-analysis.md"


def main() -> None:
    L: list[str] = []
    add = L.append

    add("# KV cache analysis\n")
    add("Generated by `python scripts/generate_tables.py`. Do not edit by hand.\n")
    add("All figures assume fp16/bf16 KV (2 bytes) unless stated.\n")

    add("\n## 1. Cache growth per token\n")
    add("`2 x n_layers x n_kv_heads x d_head x dtype_bytes`\n")
    add("| model | layers | q-heads | kv-heads | group | KV/token | KV @ 8k |")
    add("|---|---|---|---|---|---|---|")
    for c in MODELS.values():
        add(f"| {c.name} | {c.n_layers} | {c.n_heads} | {c.n_kv_heads} | "
            f"{c.gqa_group_size}x | {c.kv_bytes_per_token():,} B | {c.kv_gib(8192):.2f} GiB |")

    add("\n## 2. What GQA actually bought\n")
    add("Same model, hypothetically built with one KV head per query head.\n")
    add("| model | GQA KV/token | MHA KV/token | saving |")
    add("|---|---|---|---|")
    for c in MODELS.values():
        m = hypothetical_mha(c)
        add(f"| {c.name} | {c.kv_bytes_per_token():,} B | {m.kv_bytes_per_token():,} B | "
            f"{m.kv_bytes_per_token() / c.kv_bytes_per_token():.0f}x |")

    add("\n## 3. Concurrency ceiling\n")
    add("Max concurrent sequences for Llama-3-8B, by context length and GPU.\n")
    add("Assumes 16 GiB weights and 2 GiB activation/framework overhead.\n")
    c = MODELS["llama-3-8b"]
    gpus = ["A100-40G", "A100-80G", "H100-80G", "H200-141G"]
    add("| context | " + " | ".join(gpus) + " |")
    add("|---|" + "---|" * len(gpus))
    for n in (2048, 4096, 8192, 16384, 32768):
        add(f"| {n:,} | " + " | ".join(str(c.max_batch(n, GPUS[g])) for g in gpus) + " |")

    add("\n**This table is the answer to \"why did the deployment cap context at 8k?\"** "
        "The cap is not arbitrary: doubling context halves concurrency, which halves "
        "throughput and doubles cost per request. A context limit is a throughput "
        "decision wearing a correctness costume.\n")

    add("\n## 4. When the cache overtakes the weights\n")
    add("KV cache as a multiple of weight memory, Llama-3-8B (16 GiB weights).\n")
    batches = (1, 8, 32)
    add("| context | " + " | ".join(f"batch {b}" for b in batches) + " |")
    add("|---|" + "---|" * len(batches))
    for n in (4096, 8192, 32768, 131072):
        add(f"| {n:,} | " + " | ".join(f"{c.kv_vs_weights(n, b):.2f}x" for b in batches) + " |")

    add("\nAt long context and realistic batch the cache is several times the "
        "model. Any capacity plan that budgets only for weights is wrong by "
        "more than an order of magnitude.\n")

    add("\n## 5. KV-cache quantization\n")
    add("Llama-3-8B @ 8k on H100-80G. Halving KV bytes roughly doubles concurrency, "
        "which is why KV-cache quantization is often a bigger win than weight "
        "quantization at long context.\n")
    add("| KV dtype | bytes | KV @ 8k | max batch |")
    add("|---|---|---|---|")
    for label, nb in (("fp16/bf16", 2), ("fp8", 1)):
        add(f"| {label} | {nb} | {c.kv_gib(8192, 1, nb):.2f} GiB | "
            f"{c.max_batch(8192, GPUS['H100-80G'], nb)} |")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(OUT.parent.parent)}  ({len(L)} lines)")


if __name__ == "__main__":
    main()
